services:
  - type: web
    name: cryptoinvest-backend
    env: python
    region: frankfurt
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd backend && gunicorn invest_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.25
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: cryptoinvest-db
          property: connectionString
