services:
  - type: web
    name: cryptoinvest-backend
    runtime: python
    pythonVersion: 3.12.1
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && python create_superuser.py && gunicorn invest_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '*.onrender.com,visafin-gest.org,www.visafin-gest.org,api.visafin-gest.org,*.vercel.app'
      - key: DATABASE_URL
        fromDatabase:
          name: cryptoinvest-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        value: '562113266712-p7i84kjqmnri2ihs3lqd1d3saqh8von0.apps.googleusercontent.com'
      - key: SITE_URL
        value: 'https://visafin-gest.org'

databases:
  - name: cryptoinvest-db
    databaseName: cryptoinvest
    user: cryptoinvest
