services:
  - type: web
    name: cryptoinvest-backend
    env: python
    region: frankfurt
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.25
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cryptoinvest-db
          property: connectionString
